name: cafe5_mworker
description: "Mobile worker module of cafe5."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  package_info_plus: ^6.0.0
  intl: ^0.19.0
  http: ^1.1.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true
  assets:
    - assets/